### ISSUE TITLE
Find a better name for the library

### ISSUE THREAD

**Issue by gpetiot** [gpetiot/sexp-parse#7]
Before submitting the package to opam (I could also add more tests but that's not the subject :D).

I'm not really satisfied with `sexp-parse`, it sounds too close to `parsexp`, I was thinking of something stressing out the absence of base dependency, or just the no bloat of the library, like:
- xs-sexp (extra small)
- xs-sexplib
- sexplib-light
- sexplib-nobase
- sexply (sounds more like an adverb, and sounds nice)
- sexpily (same)
- ...

Maybe I'm getting ahead of myself, but I think a small lib like this worth having on opam and I'd rather not change the name after getting it on opam.
cc @julow @Leonidas-from-XIV @emillon in case any of you has some ideas, I don't know who to ping

**Comment by Julow** [comment]
That's the hardest part of developing software !

What about `ezsexp` ? There are mirage libraries named similarly: `ezjsonm` and `ezxmlm`, although these libraries are defining an abstraction on top of an existing parsing library and not doing parsing.

I dislike `sexplib-*` because it feels like appropriating a namespace that is already taken. For the same reason I wouldn't recommend `sexpm`, which correspond to stream parsing, I think.

I like `xs-sexplib` because the main feature of the library is to be small. The reference to sexplib is ok because it's working with `sexplib0`.

**Comment by Leonidas-from-XIV** [comment]
I wouldn't go with `ez-` because that's usually "libraries to make it easier to work with the non-`ez-` library". As a user I would immediately think this is something else than it is. I also wouldn't go for `nobase` because it seems weird to focus on what the library isn't, it is much better to focus on what it is. I agree with @Julow that using the `sexplib-*` feels like it would be a JST thing.

What about `dietsexplib`? That conveys the spirit of being tiny (reminds me of `dietlibc` which is not a great `libc` but has a good name). Or something with `feather`? `light-paren`? Or just `paren`?

One could also go for `sxplib` in a way that `msgpck` did to distinguish itself from `msgpack` but I think it makes it hard to distinguish in speech.

**Comment by emillon** [comment]
I'm going to go one extra step and ask the question: if this library gets released to opam, how to justify its existence? For 2 libraries to do the exact same thing, there must be a question with a clear answer that points you to `parsexp` or this library.

If the reason is just that `parsexp` depends on `base`, we need to find why. From a quick grep it looks like `parsexp` only uses `base.caml` which is a renaming layer on top of `Stdlib`. I'm sure it's possible to discuss about removing that dependency. `parsexp_io` has more difficult dependencies but I think that in the use case that you had in mind, parsing from a string is no issue.

What do you think?

**Comment by gpetiot** [comment]
I agree about that, I tried to stress about the no `base` dependency because that was my motivation to working on it (but it was fun anyway). I can try to drop a "would it be possible to not use base" issue on slack or github and hope I get an answer, but I fear it's gonna be something along "easier for us, better naming conventions".

**Comment by gpetiot** [comment]
After asking on slack it's very unlikely to be done.
Maybe I should put the opam publish on pause until someone finds it useful.
